INSERT INTO ROLE (ROLE_NAME) VALUES ('CLIENT');
INSERT INTO ROLE (ROLE_NAME) VALUES ('EMPLOYEE');
INSERT INTO ROLE (ROLE_NAME) VALUES ('ADMIN');

INSERT INTO EMPLOYEE (BONUS,GROSS_WAGE,WORKING_HOURS) VALUES (350.0,3000.0,'FULL TIME (1)');
INSERT INTO EMPLOYEE (BONUS,GROSS_WAGE,WORKING_HOURS) VALUES (200.0,2300.0,'PART TIME (4/5)');
INSERT INTO EMPLOYEE (BONUS,GROSS_WAGE,WORKING_HOURS) VALUES (0.0,3100.00,'PART TIME (3/4)');

INSERT INTO WEB_USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMPLOYEE_ID) VALUES ('xel@secv.com','Weronika','Lizak','$2y$12$/mWrBYYzV8p3kHHzC8Dize8WBQGb9DiF3ta5kRcyt0WDbMnx4anr2','wera12',1);
INSERT INTO WEB_USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMPLOYEE_ID) VALUES ('prag@ges.com','Marek','Chad','$2y$12$uvvh5WU9LqFY/439b4JS/.8KCXrTkYb5KnSEycRQXoLanWMi3EQn2','mark12',null);
INSERT INTO WEB_USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMPLOYEE_ID) VALUES ('jfock.fao@taikz.com','Marcin','Wilgowski','$2y$12$yCEqKFUY9JYG9a8nB5EN3OqfOTqw6OySBwZ4SXEuhcFKm95LNj5B2','marceg12',2);
INSERT INTO WEB_USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMPLOYEE_ID) VALUES ('marawaj@pery.com','Bruce','Willis','$2y$12$g9j6tNeQOIExOrTxQ8LGKuKKCh9MCL9yVplVMO7xyJXv9rGszINFW','bruc12',3);
INSERT INTO WEB_USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMPLOYEE_ID) VALUES ('mab@intel.com','Steven','Spielberg','$2y$12$c/.QDHbZZlOYRlPdmmQQoeTJYHGYXEhmNfC3b5895QC9kBEsZHfiK','steve12',null);
INSERT INTO WEB_USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMPLOYEE_ID) VALUES ('peste@adav.com','Angelika','Ziemia','$2y$12$A5Zl9Dac0I2CMGaD2R0MnuGy9Nek.JJvqzOKUKTU40KwoeiHQPuze','angela12',null);
INSERT INTO WEB_USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMPLOYEE_ID) VALUES ('ouz@assist.com','Natalia','Jelen','$2y$12$F9a284UlesFI.evKqNkA6uGb2ZKxNR/Cr2a8snHnLuOba0xKSwrA6','natala12',null);
INSERT INTO WEB_USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMPLOYEE_ID) VALUES ('wkam@hotmail.red','Wiktoria','Herd','$2y$12$qisuxklg4c8mgsH6f2s14OwnewabVzRNCczSLAlQfVHnFUkYZCLHC','wika12',null);
INSERT INTO WEB_USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMPLOYEE_ID) VALUES ('ciastko@eit@code.com','Kacper','Wojtkowski','$2y$12$K8O0jNayQ8OBfCFuIeeKLe0NxYdK30ZLBctRw15stQw6QPnJhtzou','kacp12',null);
INSERT INTO WEB_USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMPLOYEE_ID) VALUES ('sernik@eit@code.com','Katarzyna','Niebo','$2y$12$YQQSgUQmTj4J39Pxe7BUPObsiyxEZKl3ycq5K2lLMzX4gfwIvyKFC','kasia12',null);
INSERT INTO WEB_USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMPLOYEE_ID) VALUES ('baklazan@postpone.com','Lukasz','Sandal','$2y$12$vVuW.8BvnxzbPEkAV2YP5OpiKrsZ20rMVw.M17gqERrmuIZuQZvau','luki12',null);
INSERT INTO WEB_USER (EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMPLOYEE_ID) VALUES ('piernik@columncode.red','Anna','Raczka','$2y$12$Tb4CPxt/I0zZmTQW8NG.Y.Nx9Gwnn7CjeQEQYuG/fPjzoKuSM5YKi','ania12',null);

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1,2);

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (2,1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (2,2);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (2,3);

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (3,1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (3,2);

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (4,1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (4,2);

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (5,1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (6,1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (7,1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (8,1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (9,1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (10,1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (11,1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (12,1);

INSERT INTO OFFER (COST,DESCRIPTION,NAME) VALUES (100.0,'Lessons for anybody that never ride horse. Touching the horses ears once with the left and once with the right hand, similarly to the horses tail, neck, abdomen and shoulder blades. Embracing the horse.','Basic riding lessons');
INSERT INTO OFFER (COST,DESCRIPTION,NAME) VALUES (400.0,'Summer and winter camps for children and teenagers. We provide 2 guides/foster-fathers. More care-takers are can be assigned as a additional cost.','Summer and winter camps');
INSERT INTO OFFER (COST,DESCRIPTION,NAME) VALUES (250.0,'Events for a companies - approximately 200 people. (Tents are included)','Outdoor event');
INSERT INTO OFFER (COST,DESCRIPTION,NAME) VALUES (160.0,'Lessons for person that rides horse often and have its equipment. You must have a good seat, you must be able to harmonize with the horse, you must be able to sit on light trunking, wild galloping and stop from that wild gallop','Advanced riding lessons');
INSERT INTO OFFER (COST,DESCRIPTION,NAME) VALUES (220.0,'Only for professionals that want to train and advance their skills or competitors.The most important skill a professional rider should have is the best possible riding skill.','Professional horse riding lessons');
INSERT INTO OFFER (COST,DESCRIPTION,NAME) VALUES (900.0,'Welcome to the amazing land where the Balkans begin! Time flows differently here, to the rhythm beat by the hooves of brave horses. ','Multi-day trip');
INSERT INTO OFFER (COST,DESCRIPTION,NAME) VALUES (80.0,'Average cost of learning to drive in a circular.','Walks on horses and ponies');

INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-01-05 7:55:00'),'Pending',1,5,1);
INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-02-10 9:00:00'),'Pending',2,5,1);
INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-03-15 11:30:00'),'Pending',3,5,1);
INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-04-20 12:35:00'),'Pending',4,6,2);
INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-05-25 14:15:00'),'Pending',5,7,2);
INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-06-07 17:00:00'),'Pending',6,8,3);
INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-07-27 19:30:00'),'Pending',7,8,3);
INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-01-03 12:15:00'),'Pending',1,9,1);
INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-08-03 15:00:00'),'Pending',2,9,1);
INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-09-23 13:30:00'),'Pending',3,10,2);
INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-10-16 14:15:00'),'Pending',4,10,3);
INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-11-20 16:00:00'),'Pending',5,11,1);
INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-12-23 19:45:00'),'Pending',6,12,2);
INSERT INTO OFFER_RESERVATION (DATE_TIME,STATUS,OFFER_ID,WEB_CLIENT_ID,EMPLOYEE_ID) VALUES ((TIMESTAMP '2021-02-02 7:30:00'),'Pending',7,12,3);
